### ISSUE TITLE
Another Twitter length problem

### ISSUE THREAD

**Issue by strugee** [dper/pumptweet#33] opened 2016-06-02 20:20 UTC
Log:

```
% python3 pt.py
Reading the config file...
Logging into the Pump server...
Logging into Twitter...
Looking at Pump outbox activity...
> note (2016-05-23 21:37:46+00:00)
> note (2016-05-18 18:39:28+00:00)
/home/alex/pumptweet_community/pumptweet/MLStripper.py:10: DeprecationWarning: The value of convert_charrefs will become True in 3.5. You are encouraged to set the value explicitly.
  super().__init__()
Printing tweets...
> Greetings, pumpers!If you run your own Pump.io node, it would be a huge help if you could check nodecompat.com... https://pumpit.info/pumpio/note/_FM0E8BhTwOwz6ThhWbhqQ
Posting to Twitter...
New tweet count: 1.
---------------------------------
Twitter error.
Traceback (most recent call last):
  File "/home/alex/pumptweet_community/pumptweet/PumpTweet.py", line 136, in post_tweet
    self.twitter_api.PostUpdate(tweet)
  File "/home/alex/pumptweet_community/lib/python3.4/site-packages/twitter/api.py", line 952, in PostUpdate
    raise TwitterError("Text must be less than or equal to 140 characters.")
twitter.error.TwitterError: Text must be less than or equal to 140 characters.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pt.py", line 21, in <module>
    pumptweet.pull_and_push(halt_on_error=halt_on_error)
  File "/home/alex/pumptweet_community/pumptweet/PumpTweet.py", line 189, in pull_and_push
    self.post_tweets(tweets)
  File "/home/alex/pumptweet_community/pumptweet/PumpTweet.py", line 160, in post_tweets
    self.post_tweet(tweet)
  File "/home/alex/pumptweet_community/pumptweet/PumpTweet.py", line 140, in post_tweet
    print(e[0][0])
TypeError: 'TwitterError' object does not support indexing
```

I'm on 6b14c9bd6f9a3e251049d8a79a6c7ac05cca836b.

**Comment by dper** [comment] 2016-06-04 12:35
This is a side note, but the `TypeError: 'TwitterError' object does not support indexing` message was caused by a change in how python-twitter shows errors. It used to produce a double array; now it doesn't. Updated PumpTweet: <https://github.com/dper/pumptweet/commit/42733eae8ac0ed81a407357a44812891ecbe7ebd>.

**Comment by dper** [comment] 2016-06-04 12:49
We have had several bugs with getting the tweet length right or wrong. In <https://github.com/dper/pumptweet/commit/42733eae8ac0ed81a407357a44812891ecbe7ebd> I switched from `PostUpdate` to `PostUpdates`. This latter method creates multiple posts in the case that the desired content is too long for just one.

This doesn't fix length bugs. If the length is too long, we should try to get that figured out properly. But this lessens the effect of those bugs. Now, instead of a message not being posted at all, it should be posted in two pieces.

I am not sure why @strugee got the above error. The post is this...

```
Greetings, pumpers!If you run your own Pump.io node, it would be a huge help if you could check nodecompat.com... https://pumpit.info/pumpio/note/_FM0E8BhTwOwz6ThhWbhqQ
```
That post without the URL is 113 characters. The `...` would be shortened to an ellipsis, so it'd drop to 111. The URL would become a Twitter URL, which are currently 23 characters. So 111 + 1 + 23 = 135. This suggests there are characters in the Tweet that aren't displayed in the error message. (For example, there are two line breaks in the original note. Perhaps those are leading to a problem.)

**Comment by dper** [comment] 2016-06-04 12:55
The line breaks are indeed problematic. The code is written with the intention that only the first line is retained, but in the above note, the lines are all merged together.

**Comment by dper** [comment] 2016-06-04 13:19
In Pumpa, hard returns are `\n`, but in the web interface they are `<br>`. These were not being handled properly. In <https://github.com/dper/pumptweet/commit/1c6def2289755ed50c5d1cdac5603f1c6e523353>, `MLStripper` now handles `<br>` the same as `\n`.

This should fix the bug you hit here, @strugee.

**Closed by dper** 2016-06-04 13:19 UTC
Labels: bug

**Comment by strugee** [comment] 2016-06-05 05:14
I can confirm that this is fixed. Thanks so much as always, @dper :)
